server:
  port: 8080
  payload_max_size: 5120
service:
  max_len_chunk: 100
  max_size_chunk: 1048576
  max_collect_chunk_duration: 3s
  hosts_to_topics:
    host1: 'topic1'
    host2: 'topic2'
  kafka_brokers:
    - "localhost:9092"
