server:
  host: 0.0.0.0
  port: 8080
  payload_max_size: 5120
service:
  request:
    host_header: host
    ip_header: header
  max_len_chunk: 100
  max_size_chunk: 1048576
  max_collect_chunk_duration: 3s
  hosts_to_topics:
    host1: 'topic1'
    host2: 'topic2'
  sensitive_headers:
    - 'header1'
    - 'header2'
  sensitive_json_keys:
    - 'key1'
    - 'key2'
kafka:
  brokers:
    - 'localhost:9092'
  ack_timeout: 1s
